### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by madhunm** [NRC-NANOmi/NanoMi#3]
Hello NanoMi team,

I tried reaching out to you at NanoMi@nrc-cnrc.gc.ca; but, the email bounced.

How do I get in touch with you?

Thanks!

**Comment by 0xDBFB7** [comment]
(I'm not related to the team, this probably isn't my place - but if you still haven't got in touch maybe you could try emailing the contacts in the osf.io slides):

![Screenshot from 2021-07-18 19-06-02](https://user-images.githubusercontent.com/14041028/126084913-99e360de-f67d-4c3d-b69a-d71a20d4c8f3.png)

**Comment by ccBrita** [comment]
Please check readme, it has contact info at the bottom
